rvm:
  - 2.1.0
  - 2.0.0
  - 1.9.3

gemfile:
  - Gemfile
  - Gemfile_rails40
  - Gemfile_rails31
  - Gemfile_rails30

script: "bundle exec rake test:units"

notifications:
  email:
    - payments-dev@shopify.com
    - nathaniel@talbott.ws
